#!/bin/bash

# Create the cron log file
mkdir -p /var/log/cron

file=/var/www/cron.conf

# Make sure there is a empty line @ EOF
echo '' >> ${file}

if [ -f ${file} ]; then
    # Make sure there is a empty line @ EOF
    if [ ! -z "$(tail -c 1 "${file}")" ]
    then
        echo '' >> ${file}
    fi

    # Set the cron to run
    crontab ${file}
fi

# Start the cron service
crond

# Disable default services
# rm -rf /etc/services.d/nginx
rm -rf /etc/services.d/php7

/init